import { Component, OnInit } from '@angular/core';
import {
  IWeatherDaily,
  IWeatherHightLights,
  IWeatherToday,
} from './models/weather';
import { WeatherService } from './services/weather.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  title = 'WeatherApp';

  weatherInfoToday: IWeatherToday;
  weatherInfoDaily: any;
  weatherHightlights = {} as IWeatherHightLights;

  location: string = 'Saint-Petersburg';

  constructor(private weatherService: WeatherService) {}

  initWeatherInfo(location: string): void {
    this.weatherService
      .getWeatherTodayByLocationName(location)
      .subscribe((infoToday) => {
        this.weatherInfoToday = infoToday;
        this.weatherInfoToday.location.localtime = new Date(
          infoToday.location.localtime
        );

        // weatherHightlight init start
        this.weatherHightlights.uvIndex = this.weatherInfoToday.current.uv;
        this.weatherHightlights.feelslike_c =
          this.weatherInfoToday.current.feelslike_c;
        this.weatherHightlights.humidity =
          this.weatherInfoToday.current.humidity;
        this.weatherHightlights.vis_km = this.weatherInfoToday.current.vis_km;
        this.weatherHightlights.wind_kph =
          this.weatherInfoToday.current.wind_kph;
      });

    this.weatherService
      .getWeatherDailyByLocationName(location)
      .subscribe((infoDaily) => {
        this.weatherInfoDaily = infoDaily;

        // this.weatherInfoDaily = {
        //   "timelines": {
        //     "daily": [
        //       {
        //         "time": "2023-04-25T00:00:00Z",
        //         "values": {
        //           "cloudBaseAvg": 1.21,
        //           "cloudBaseMax": 1.75,
        //           "cloudBaseMin": 0.39,
        //           "cloudCeilingAvg": 1.84,
        //           "cloudCeilingMax": 4.8,
        //           "cloudCeilingMin": 0.79,
        //           "cloudCoverAvg": 77.88,
        //           "cloudCoverMax": 100,
        //           "cloudCoverMin": 0,
        //           "dewPointAvg": 9.67,
        //           "dewPointMax": 13.96,
        //           "dewPointMin": 4.5,
        //           "evapotranspirationAvg": 0.148,
        //           "evapotranspirationMax": 0.492,
        //           "evapotranspirationMin": 0.034,
        //           "evapotranspirationSum": 3.546,
        //           "freezingRainIntensityAvg": 0,
        //           "freezingRainIntensityMax": 0,
        //           "freezingRainIntensityMin": 0,
        //           "humidityAvg": 70.05,
        //           "humidityMax": 92.36,
        //           "humidityMin": 47,
        //           "iceAccumulationAvg": 0,
        //           "iceAccumulationLweAvg": 0,
        //           "iceAccumulationLweMax": 0,
        //           "iceAccumulationLweMin": 0,
        //           "iceAccumulationLweSum": 0,
        //           "iceAccumulationMax": 0,
        //           "iceAccumulationMin": 0,
        //           "iceAccumulationSum": 0,
        //           "moonriseTime": null,
        //           "moonsetTime": "2023-04-25T14:46:38Z",
        //           "precipitationProbabilityAvg": 10.8,
        //           "precipitationProbabilityMax": 70,
        //           "precipitationProbabilityMin": 0,
        //           "pressureSurfaceLevelAvg": 1018.5,
        //           "pressureSurfaceLevelMax": 1024.96,
        //           "pressureSurfaceLevelMin": 1010.2,
        //           "rainAccumulationAvg": 0.13,
        //           "rainAccumulationLweAvg": 0.13,
        //           "rainAccumulationLweMax": 0.86,
        //           "rainAccumulationLweMin": 0,
        //           "rainAccumulationMax": 0.86,
        //           "rainAccumulationMin": 0,
        //           "rainAccumulationSum": 3.06,
        //           "rainIntensityAvg": 0.11,
        //           "rainIntensityMax": 0.86,
        //           "rainIntensityMin": 0,
        //           "sleetAccumulationAvg": 0,
        //           "sleetAccumulationLweAvg": 0,
        //           "sleetAccumulationLweMax": 0,
        //           "sleetAccumulationLweMin": 0,
        //           "sleetAccumulationLweSum": 0,
        //           "sleetAccumulationMax": 0,
        //           "sleetAccumulationMin": 0,
        //           "sleetIntensityAvg": 0,
        //           "sleetIntensityMax": 0,
        //           "sleetIntensityMin": 0,
        //           "snowAccumulationAvg": 0,
        //           "snowAccumulationLweAvg": 0,
        //           "snowAccumulationLweMax": 0,
        //           "snowAccumulationLweMin": 0,
        //           "snowAccumulationLweSum": 0,
        //           "snowAccumulationMax": 0,
        //           "snowAccumulationMin": 0,
        //           "snowAccumulationSum": 0,
        //           "snowIntensityAvg": 0,
        //           "snowIntensityMax": 0,
        //           "snowIntensityMin": 0,
        //           "sunriseTime": "2023-04-24T19:58:00Z",
        //           "sunsetTime": "2023-04-25T09:19:00Z",
        //           "temperatureApparentAvg": 15.36,
        //           "temperatureApparentMax": 18,
        //           "temperatureApparentMin": 12.69,
        //           "temperatureAvg": 15.36,
        //           "temperatureMax": 18,
        //           "temperatureMin": 12.69,
        //           "uvHealthConcernAvg": 1,
        //           "uvHealthConcernMax": 3,
        //           "uvHealthConcernMin": 0,
        //           "uvIndexAvg": 1,
        //           "uvIndexMax": 8,
        //           "uvIndexMin": 0,
        //           "visibilityAvg": 12.25,
        //           "visibilityMax": 16,
        //           "visibilityMin": 3.91,
        //           "weatherCodeMax": 1001,
        //           "weatherCodeMin": 1001,
        //           "windDirectionAvg": 133.67,
        //           "windGustAvg": 3.52,
        //           "windGustMax": 8.64,
        //           "windGustMin": 1.38,
        //           "windSpeedAvg": 2.2,
        //           "windSpeedMax": 5.95,
        //           "windSpeedMin": 0.81
        //         }
        //       },
        //       {
        //         "time": "2023-04-26T00:00:00Z",
        //         "values": {
        //           "cloudBaseAvg": 0.51,
        //           "cloudBaseMax": 1.7,
        //           "cloudBaseMin": 0,
        //           "cloudCeilingAvg": 1.38,
        //           "cloudCeilingMax": 6.05,
        //           "cloudCeilingMin": 0,
        //           "cloudCoverAvg": 73.05,
        //           "cloudCoverMax": 100,
        //           "cloudCoverMin": 0.78,
        //           "dewPointAvg": 9.98,
        //           "dewPointMax": 18.02,
        //           "dewPointMin": 3.3,
        //           "evapotranspirationAvg": 0.105,
        //           "evapotranspirationMax": 0.24,
        //           "evapotranspirationMin": 0.051,
        //           "evapotranspirationSum": 2.513,
        //           "freezingRainIntensityAvg": 0,
        //           "freezingRainIntensityMax": 0,
        //           "freezingRainIntensityMin": 0,
        //           "humidityAvg": 70.99,
        //           "humidityMax": 88.41,
        //           "humidityMin": 52.73,
        //           "iceAccumulationAvg": 0,
        //           "iceAccumulationLweAvg": 0,
        //           "iceAccumulationLweMax": 0,
        //           "iceAccumulationLweMin": 0,
        //           "iceAccumulationLweSum": 0,
        //           "iceAccumulationMax": 0,
        //           "iceAccumulationMin": 0,
        //           "iceAccumulationSum": 0,
        //           "moonriseTime": "2023-04-26T00:07:06Z",
        //           "moonsetTime": "2023-04-26T15:32:21Z",
        //           "precipitationProbabilityAvg": 5,
        //           "precipitationProbabilityMax": 15,
        //           "precipitationProbabilityMin": 0,
        //           "pressureSurfaceLevelAvg": 1005.78,
        //           "pressureSurfaceLevelMax": 1016.81,
        //           "pressureSurfaceLevelMin": 998.22,
        //           "rainAccumulationAvg": 0.6,
        //           "rainAccumulationLweAvg": 0.6,
        //           "rainAccumulationLweMax": 3.91,
        //           "rainAccumulationLweMin": 0,
        //           "rainAccumulationMax": 3.91,
        //           "rainAccumulationMin": 0,
        //           "rainAccumulationSum": 14.29,
        //           "rainIntensityAvg": 0.61,
        //           "rainIntensityMax": 3.91,
        //           "rainIntensityMin": 0,
        //           "sleetAccumulationAvg": 0,
        //           "sleetAccumulationLweAvg": 0,
        //           "sleetAccumulationLweMax": 0,
        //           "sleetAccumulationLweMin": 0,
        //           "sleetAccumulationLweSum": 0,
        //           "sleetAccumulationMax": 0,
        //           "sleetAccumulationMin": 0,
        //           "sleetIntensityAvg": 0,
        //           "sleetIntensityMax": 0,
        //           "sleetIntensityMin": 0,
        //           "snowAccumulationAvg": 0,
        //           "snowAccumulationLweAvg": 0,
        //           "snowAccumulationLweMax": 0,
        //           "snowAccumulationLweMin": 0,
        //           "snowAccumulationLweSum": 0,
        //           "snowAccumulationMax": 0,
        //           "snowAccumulationMin": 0,
        //           "snowAccumulationSum": 0,
        //           "snowIntensityAvg": 0,
        //           "snowIntensityMax": 0,
        //           "snowIntensityMin": 0,
        //           "sunriseTime": "2023-04-25T19:57:00Z",
        //           "sunsetTime": "2023-04-26T09:19:00Z",
        //           "temperatureApparentAvg": 15.35,
        //           "temperatureApparentMax": 20.38,
        //           "temperatureApparentMin": 10.52,
        //           "temperatureAvg": 15.35,
        //           "temperatureMax": 20.38,
        //           "temperatureMin": 10.52,
        //           "uvHealthConcernAvg": 0,
        //           "uvHealthConcernMax": 1,
        //           "uvHealthConcernMin": 0,
        //           "uvIndexAvg": 1,
        //           "uvIndexMax": 3,
        //           "uvIndexMin": 0,
        //           "visibilityAvg": 10.85,
        //           "visibilityMax": 16,
        //           "visibilityMin": 1.89,
        //           "weatherCodeMax": 1001,
        //           "weatherCodeMin": 1001,
        //           "windDirectionAvg": 267.42,
        //           "windGustAvg": 13.6,
        //           "windGustMax": 22.71,
        //           "windGustMin": 7.75,
        //           "windSpeedAvg": 9.42,
        //           "windSpeedMax": 15.66,
        //           "windSpeedMin": 5.44
        //         }
        //       },
        //       {
        //         "time": "2023-04-27T00:00:00Z",
        //         "values": {
        //           "cloudBaseAvg": 0.19,
        //           "cloudBaseMax": 2.28,
        //           "cloudBaseMin": 0,
        //           "cloudCeilingAvg": 0,
        //           "cloudCeilingMax": 0,
        //           "cloudCeilingMin": 0,
        //           "cloudCoverAvg": 7.52,
        //           "cloudCoverMax": 45.31,
        //           "cloudCoverMin": 0,
        //           "dewPointAvg": 9.53,
        //           "dewPointMax": 12.31,
        //           "dewPointMin": 4.65,
        //           "evapotranspirationAvg": 0.205,
        //           "evapotranspirationMax": 0.545,
        //           "evapotranspirationMin": 0.047,
        //           "evapotranspirationSum": 4.93,
        //           "freezingRainIntensityAvg": 0,
        //           "freezingRainIntensityMax": 0,
        //           "freezingRainIntensityMin": 0,
        //           "humidityAvg": 64.67,
        //           "humidityMax": 82.84,
        //           "humidityMin": 33.8,
        //           "iceAccumulationAvg": 0,
        //           "iceAccumulationLweAvg": 0,
        //           "iceAccumulationLweMax": 0,
        //           "iceAccumulationLweMin": 0,
        //           "iceAccumulationLweSum": 0,
        //           "iceAccumulationMax": 0,
        //           "iceAccumulationMin": 0,
        //           "iceAccumulationSum": 0,
        //           "moonriseTime": "2023-04-27T01:03:38Z",
        //           "moonsetTime": "2023-04-27T16:11:35Z",
        //           "precipitationProbabilityAvg": 0,
        //           "precipitationProbabilityMax": 0,
        //           "precipitationProbabilityMin": 0,
        //           "pressureSurfaceLevelAvg": 1020.65,
        //           "pressureSurfaceLevelMax": 1022.47,
        //           "pressureSurfaceLevelMin": 1017.64,
        //           "rainAccumulationAvg": 0,
        //           "rainAccumulationLweAvg": 0,
        //           "rainAccumulationLweMax": 0,
        //           "rainAccumulationLweMin": 0,
        //           "rainAccumulationMax": 0,
        //           "rainAccumulationMin": 0,
        //           "rainAccumulationSum": 0,
        //           "rainIntensityAvg": 0,
        //           "rainIntensityMax": 0,
        //           "rainIntensityMin": 0,
        //           "sleetAccumulationAvg": 0,
        //           "sleetAccumulationLweAvg": 0,
        //           "sleetAccumulationLweMax": 0,
        //           "sleetAccumulationLweMin": 0,
        //           "sleetAccumulationLweSum": 0,
        //           "sleetAccumulationMax": 0,
        //           "sleetAccumulationMin": 0,
        //           "sleetIntensityAvg": 0,
        //           "sleetIntensityMax": 0,
        //           "sleetIntensityMin": 0,
        //           "snowAccumulationAvg": 0,
        //           "snowAccumulationLweAvg": 0,
        //           "snowAccumulationLweMax": 0,
        //           "snowAccumulationLweMin": 0,
        //           "snowAccumulationLweSum": 0,
        //           "snowAccumulationMax": 0,
        //           "snowAccumulationMin": 0,
        //           "snowAccumulationSum": 0,
        //           "snowIntensityAvg": 0,
        //           "snowIntensityMax": 0,
        //           "snowIntensityMin": 0,
        //           "sunriseTime": "2023-04-26T19:56:00Z",
        //           "sunsetTime": "2023-04-27T09:20:00Z",
        //           "temperatureApparentAvg": 16.82,
        //           "temperatureApparentMax": 21.21,
        //           "temperatureApparentMin": 14.28,
        //           "temperatureAvg": 16.82,
        //           "temperatureMax": 21.21,
        //           "temperatureMin": 14.28,
        //           "uvHealthConcernAvg": 1,
        //           "uvHealthConcernMax": 3,
        //           "uvHealthConcernMin": 0,
        //           "uvIndexAvg": 2,
        //           "uvIndexMax": 8,
        //           "uvIndexMin": 0,
        //           "visibilityAvg": 15.69,
        //           "visibilityMax": 16,
        //           "visibilityMin": 11.1,
        //           "weatherCodeMax": 1000,
        //           "weatherCodeMin": 1000,
        //           "windDirectionAvg": 241.22,
        //           "windGustAvg": 9.55,
        //           "windGustMax": 11.6,
        //           "windGustMin": 5.66,
        //           "windSpeedAvg": 6.44,
        //           "windSpeedMax": 7.85,
        //           "windSpeedMin": 2.72
        //         }
        //       },
        //       {
        //         "time": "2023-04-28T00:00:00Z",
        //         "values": {
        //           "cloudBaseAvg": 5.46,
        //           "cloudBaseMax": 8.32,
        //           "cloudBaseMin": 0,
        //           "cloudCeilingAvg": 4.04,
        //           "cloudCeilingMax": 8.64,
        //           "cloudCeilingMin": 0,
        //           "cloudCoverAvg": 79.87,
        //           "cloudCoverMax": 100,
        //           "cloudCoverMin": 17.97,
        //           "dewPointAvg": 11.85,
        //           "dewPointMax": 13.42,
        //           "dewPointMin": 9.67,
        //           "evapotranspirationAvg": 0.207,
        //           "evapotranspirationMax": 0.491,
        //           "evapotranspirationMin": 0.093,
        //           "evapotranspirationSum": 4.969,
        //           "freezingRainIntensityAvg": 0,
        //           "freezingRainIntensityMax": 0,
        //           "freezingRainIntensityMin": 0,
        //           "humidityAvg": 66.49,
        //           "humidityMax": 71.59,
        //           "humidityMin": 55.62,
        //           "iceAccumulationAvg": 0,
        //           "iceAccumulationLweAvg": 0,
        //           "iceAccumulationLweMax": 0,
        //           "iceAccumulationLweMin": 0,
        //           "iceAccumulationLweSum": 0,
        //           "iceAccumulationMax": 0,
        //           "iceAccumulationMin": 0,
        //           "iceAccumulationSum": 0,
        //           "moonriseTime": "2023-04-28T02:02:12Z",
        //           "moonsetTime": "2023-04-28T16:45:11Z",
        //           "precipitationProbabilityAvg": 0,
        //           "precipitationProbabilityMax": 0,
        //           "precipitationProbabilityMin": 0,
        //           "pressureSurfaceLevelAvg": 1017.47,
        //           "pressureSurfaceLevelMax": 1022.09,
        //           "pressureSurfaceLevelMin": 1013.98,
        //           "rainAccumulationAvg": 0,
        //           "rainAccumulationLweAvg": 0,
        //           "rainAccumulationLweMax": 0,
        //           "rainAccumulationLweMin": 0,
        //           "rainAccumulationMax": 0,
        //           "rainAccumulationMin": 0,
        //           "rainAccumulationSum": 0,
        //           "rainIntensityAvg": 0,
        //           "rainIntensityMax": 0,
        //           "rainIntensityMin": 0,
        //           "sleetAccumulationAvg": 0,
        //           "sleetAccumulationLweAvg": 0,
        //           "sleetAccumulationLweMax": 0,
        //           "sleetAccumulationLweMin": 0,
        //           "sleetAccumulationLweSum": 0,
        //           "sleetAccumulationMax": 0,
        //           "sleetAccumulationMin": 0,
        //           "sleetIntensityAvg": 0,
        //           "sleetIntensityMax": 0,
        //           "sleetIntensityMin": 0,
        //           "snowAccumulationAvg": 0,
        //           "snowAccumulationLweAvg": 0,
        //           "snowAccumulationLweMax": 0,
        //           "snowAccumulationLweMin": 0,
        //           "snowAccumulationLweSum": 0,
        //           "snowAccumulationMax": 0,
        //           "snowAccumulationMin": 0,
        //           "snowAccumulationSum": 0,
        //           "snowIntensityAvg": 0,
        //           "snowIntensityMax": 0,
        //           "snowIntensityMin": 0,
        //           "sunriseTime": "2023-04-27T19:55:00Z",
        //           "sunsetTime": "2023-04-28T09:21:00Z",
        //           "temperatureApparentAvg": 18.22,
        //           "temperatureApparentMax": 21.11,
        //           "temperatureApparentMin": 16.41,
        //           "temperatureAvg": 18.22,
        //           "temperatureMax": 21.11,
        //           "temperatureMin": 16.41,
        //           "uvHealthConcernAvg": 1,
        //           "uvHealthConcernMax": 3,
        //           "uvHealthConcernMin": 0,
        //           "uvIndexAvg": 2,
        //           "uvIndexMax": 8,
        //           "uvIndexMin": 0,
        //           "visibilityAvg": 19.56,
        //           "visibilityMax": 24.14,
        //           "visibilityMin": 16,
        //           "weatherCodeMax": 1001,
        //           "weatherCodeMin": 1001,
        //           "windDirectionAvg": 201.83,
        //           "windGustAvg": 11.13,
        //           "windGustMax": 14.71,
        //           "windGustMin": 7.69,
        //           "windSpeedAvg": 7.66,
        //           "windSpeedMax": 9.69,
        //           "windSpeedMin": 4.84
        //         }
        //       },
        //       {
        //         "time": "2023-04-29T00:00:00Z",
        //         "values": {
        //           "cloudBaseAvg": 1.56,
        //           "cloudBaseMax": 5.55,
        //           "cloudBaseMin": 0,
        //           "cloudCeilingAvg": 1.19,
        //           "cloudCeilingMax": 4.75,
        //           "cloudCeilingMin": 0,
        //           "cloudCoverAvg": 91.3,
        //           "cloudCoverMax": 100,
        //           "cloudCoverMin": 63.87,
        //           "dewPointAvg": 14.65,
        //           "dewPointMax": 18.59,
        //           "dewPointMin": 9.27,
        //           "evapotranspirationAvg": 0.2,
        //           "evapotranspirationMax": 0.5,
        //           "evapotranspirationMin": 0.037,
        //           "evapotranspirationSum": 4.799,
        //           "freezingRainIntensityAvg": 0,
        //           "freezingRainIntensityMax": 0,
        //           "freezingRainIntensityMin": 0,
        //           "humidityAvg": 73.65,
        //           "humidityMax": 91.61,
        //           "humidityMin": 50.74,
        //           "iceAccumulationAvg": 0,
        //           "iceAccumulationLweAvg": 0,
        //           "iceAccumulationLweMax": 0,
        //           "iceAccumulationLweMin": 0,
        //           "iceAccumulationLweSum": 0,
        //           "iceAccumulationMax": 0,
        //           "iceAccumulationMin": 0,
        //           "iceAccumulationSum": 0,
        //           "moonriseTime": "2023-04-29T03:00:59Z",
        //           "moonsetTime": "2023-04-29T17:13:09Z",
        //           "precipitationProbabilityAvg": 1.9,
        //           "precipitationProbabilityMax": 5,
        //           "precipitationProbabilityMin": 0,
        //           "pressureSurfaceLevelAvg": 1006.84,
        //           "pressureSurfaceLevelMax": 1014.06,
        //           "pressureSurfaceLevelMin": 1000.32,
        //           "rainAccumulationAvg": 0.07,
        //           "rainAccumulationLweAvg": 0.07,
        //           "rainAccumulationLweMax": 0.41,
        //           "rainAccumulationLweMin": 0,
        //           "rainAccumulationMax": 0.41,
        //           "rainAccumulationMin": 0,
        //           "rainAccumulationSum": 1.7,
        //           "rainIntensityAvg": 0.07,
        //           "rainIntensityMax": 0.41,
        //           "rainIntensityMin": 0,
        //           "sleetAccumulationAvg": 0,
        //           "sleetAccumulationLweAvg": 0,
        //           "sleetAccumulationLweMax": 0,
        //           "sleetAccumulationLweMin": 0,
        //           "sleetAccumulationLweSum": 0,
        //           "sleetAccumulationMax": 0,
        //           "sleetAccumulationMin": 0,
        //           "sleetIntensityAvg": 0,
        //           "sleetIntensityMax": 0,
        //           "sleetIntensityMin": 0,
        //           "snowAccumulationAvg": 0,
        //           "snowAccumulationLweAvg": 0,
        //           "snowAccumulationLweMax": 0,
        //           "snowAccumulationLweMin": 0,
        //           "snowAccumulationLweSum": 0,
        //           "snowAccumulationMax": 0,
        //           "snowAccumulationMin": 0,
        //           "snowAccumulationSum": 0,
        //           "snowIntensityAvg": 0,
        //           "snowIntensityMax": 0,
        //           "snowIntensityMin": 0,
        //           "sunriseTime": "2023-04-28T19:54:00Z",
        //           "sunsetTime": "2023-04-29T09:21:00Z",
        //           "temperatureApparentAvg": 19.78,
        //           "temperatureApparentMax": 20.86,
        //           "temperatureApparentMin": 18.42,
        //           "temperatureAvg": 19.78,
        //           "temperatureMax": 20.86,
        //           "temperatureMin": 18.42,
        //           "uvHealthConcernAvg": 1,
        //           "uvHealthConcernMax": 3,
        //           "uvHealthConcernMin": 0,
        //           "uvIndexAvg": 2,
        //           "uvIndexMax": 8,
        //           "uvIndexMin": 0,
        //           "visibilityAvg": 23.09,
        //           "visibilityMax": 24.14,
        //           "visibilityMin": 16.57,
        //           "weatherCodeMax": 1001,
        //           "weatherCodeMin": 1001,
        //           "windDirectionAvg": 189.65,
        //           "windGustAvg": 17.55,
        //           "windGustMax": 23.83,
        //           "windGustMin": 7.05,
        //           "windSpeedAvg": 12.52,
        //           "windSpeedMax": 15.99,
        //           "windSpeedMin": 6.32
        //         }
        //       }
        //     ]
        //   },
        //   "location": {
        //     "lat": 35.72515106201172,
        //     "lon": 139.76300048828125,
        //     "name": "NEWYORK, 不忍通り, 千駄木三丁目, 文京区, 東京都, 113-0022, 日本",
        //     "type": "yes"
        //   }
        // }

        // weatherHighlight init end
        this.weatherHightlights.sunriseTime =
          this.weatherInfoDaily.timelines.daily[0].values.sunriseTime;
        this.weatherHightlights.sunriseTime =
          this.weatherInfoDaily.timelines.daily[0].values.sunsetTime;

        for (let i = 0; i < infoDaily.timelines.daily.length; i++) {
          //set time
          this.weatherInfoDaily.timelines.daily[i].time = new Date(
            infoDaily.timelines.daily[i].time
          );

          // set sunset time
          this.weatherInfoDaily.timelines.daily[i].values.sunsetTime = new Date(
            infoDaily.timelines.daily[i].values.sunsetTime
          );

          // set sunrise time
          this.weatherInfoDaily.timelines.daily[i].values.sunriseTime =
            new Date(infoDaily.timelines.daily[i].values.sunriseTime);

          // set moonset time
          this.weatherInfoDaily.timelines.daily[i].values.moonsetTime =
            new Date(infoDaily.timelines.daily[i].values.moonsetTime);

          // set moonrise time
          this.weatherInfoDaily.timelines.daily[i].values.moonriseTime =
            new Date(infoDaily.timelines.daily[i].values.moonriseTime);
        }
      });
  }

  update(location: string) {
    this.location = location;
    this.initWeatherInfo(location);
  }

  ngOnInit(): void {
    this.initWeatherInfo(this.location);
  }
}
